export const ARTISTS = [
  'Abz J Harding',
  'Allen Douglas',
  'Allen Williams',
  'Anna Pavleeva',
  'Antonio José Manzanedo',
  'Ashley Mackenzie',
  'Aurore Folny',
  'Bartek Fedyczak',
  'Billy Christian',
  'Bryan Sola',
  'Cacho Rubione',
  'Chris Ostrowski',
  'Chris Rallis',
  'Cristi Balanescu',
  'Cristy Balanescu',
  'Dan Mumford',
  'Dan Watson',
  'David Szabo',
  'Denys Tsiperko',
  'Diana Franco',
  'Ekaterina Burmak',
  'Eli Minaya',
  'Fariba Khamseh',
  'Fernando Falcone',
  'Goñi Montes',
  'Helge C. Balzer',
  'Igor Krstic',
  'Inkognit',
  'Irina Nordsol',
  'Ivan Shavrin',
  'Jack Hughes',
  'James Ryman',
  'Jana Heidersdorf',
  'Jeremy Wilson',
  'Johan Grenier',
  'John Stanko',
  'John Tedrick',
  'Josh Newton',
  'Joshua Raphael',
  'Josu Hernaiz',
  'Julian Kok Joon Wen',
  'Julie Dillon',
  'Kekai Kotaki',
  'Lenka Simecková & Scott Okumura',
  'Leonardo Borazio',
  'Magali Villeneuve',
  'Marco Gorlei',
  'Marie Magny',
  'Marta Nael',
  'Martin de Diego Sádaba',
  'Maxime Minard',
  'Michele Giorgi',
  'Miklós Ligeti',
  'Miranda Meeks',
  'Mirko Failoni',
  'Nino Vecia',
  'Randy Gallegos',
  'Raymond Bonilla',
  'Richard Luong',
  'Sam Burley',
  'Sam Wolfe Connelly',
  'Scott Buoncristiano',
  'Sergey Glushakov',
  'Titus Lunter',
  'Toni Infante',
  'Vance Kelly',
  'Zezhou Chen',
]
